; NOTE: Assertions have been autogenerated by utils/update_analyze_test_checks.py UTC_ARGS: --version 2
; RUN: opt -disable-output "-passes=print<scalar-evolution>" < %s 2>&1 | FileCheck %s

; Tests for recognition of SCEVConditionalAddRecExpr from the "select form":
;
;   j = phi(Start, select(Cond, j + Step, j))
;       -> { Start, +[Cond], Step }<%loop>
;
; The select form is what appears after simplifycfg/instcombine have merged
; a conditional update into a single block. The split-CFG / phi-merge form
; (as produced by clang before those passes run) is covered separately.

; Canonical: j advances by 1 when cond is true.
define void @conditional_iv_select(i32 %n) {
; CHECK-LABEL: 'conditional_iv_select'
; CHECK-NEXT:  Classifying expressions for: @conditional_iv_select
; CHECK-NEXT:    %i = phi i32 [ 0, %entry ], [ %i.next, %loop ]
; CHECK-NEXT:    --> {0,+,1}<nuw><nsw><%loop> U: [0,-2147483648) S: [0,-2147483648) Exits: (-1 + %n) LoopDispositions: { %loop: Computable }
; CHECK-NEXT:    %j = phi i32 [ 0, %entry ], [ %j.next, %loop ]
; CHECK-NEXT:    --> {0,+[%cond],1}<%loop> U: full-set S: full-set Exits: <<Unknown>> LoopDispositions: { %loop: Computable }
; CHECK-NEXT:    %j.plus1 = add i32 %j, 1
; CHECK-NEXT:    --> (1 + {0,+[%cond],1}<%loop>) U: full-set S: full-set Exits: <<Unknown>> LoopDispositions: { %loop: Computable }
; CHECK-NEXT:    %j.next = select i1 %cond, i32 %j.plus1, i32 %j
; CHECK-NEXT:    --> %j.next U: full-set S: full-set Exits: <<Unknown>> LoopDispositions: { %loop: Variant }
; CHECK-NEXT:    %i.next = add nuw nsw i32 %i, 1
; CHECK-NEXT:    --> {1,+,1}<nuw><nsw><%loop> U: [1,-2147483648) S: [1,-2147483648) Exits: %n LoopDispositions: { %loop: Computable }
; CHECK-NEXT:  Determining loop execution counts for: @conditional_iv_select
; CHECK-NEXT:  Loop %loop: backedge-taken count is (-1 + %n)
; CHECK-NEXT:  Loop %loop: constant max backedge-taken count is i32 -1
; CHECK-NEXT:  Loop %loop: symbolic max backedge-taken count is (-1 + %n)
; CHECK-NEXT:  Loop %loop: Trip multiple is 1
;
entry:
  br label %loop

loop:
  %i = phi i32 [ 0, %entry ], [ %i.next, %loop ]
  %j = phi i32 [ 0, %entry ], [ %j.next, %loop ]
  %cond = icmp sgt i32 %i, 10
  %j.plus1 = add i32 %j, 1
  %j.next = select i1 %cond, i32 %j.plus1, i32 %j
  %i.next = add nuw nsw i32 %i, 1
  %done = icmp eq i32 %i.next, %n
  br i1 %done, label %exit, label %loop

exit:
  ret void
}

; Swapped select: TrueValue == phi, FalseValue == phi+step. Cond gets negated.
define void @conditional_iv_select_swapped(i32 %n, i32 %step) {
; CHECK-LABEL: 'conditional_iv_select_swapped'
; CHECK-NEXT:  Classifying expressions for: @conditional_iv_select_swapped
; CHECK-NEXT:    %i = phi i32 [ 0, %entry ], [ %i.next, %loop ]
; CHECK-NEXT:    --> {0,+,1}<nuw><nsw><%loop> U: [0,-2147483648) S: [0,-2147483648) Exits: (-1 + %n) LoopDispositions: { %loop: Computable }
; CHECK-NEXT:    %j = phi i32 [ 0, %entry ], [ %j.next, %loop ]
; CHECK-NEXT:    --> {0,+[(true + %cond)],%step}<%loop> U: full-set S: full-set Exits: <<Unknown>> LoopDispositions: { %loop: Computable }
; CHECK-NEXT:    %j.plus.step = add i32 %j, %step
; CHECK-NEXT:    --> ({0,+[(true + %cond)],%step}<%loop> + %step) U: full-set S: full-set Exits: <<Unknown>> LoopDispositions: { %loop: Computable }
; CHECK-NEXT:    %j.next = select i1 %cond, i32 %j, i32 %j.plus.step
; CHECK-NEXT:    --> %j.next U: full-set S: full-set Exits: <<Unknown>> LoopDispositions: { %loop: Variant }
; CHECK-NEXT:    %i.next = add nuw nsw i32 %i, 1
; CHECK-NEXT:    --> {1,+,1}<nuw><nsw><%loop> U: [1,-2147483648) S: [1,-2147483648) Exits: %n LoopDispositions: { %loop: Computable }
; CHECK-NEXT:  Determining loop execution counts for: @conditional_iv_select_swapped
; CHECK-NEXT:  Loop %loop: backedge-taken count is (-1 + %n)
; CHECK-NEXT:  Loop %loop: constant max backedge-taken count is i32 -1
; CHECK-NEXT:  Loop %loop: symbolic max backedge-taken count is (-1 + %n)
; CHECK-NEXT:  Loop %loop: Trip multiple is 1
;
entry:
  br label %loop

loop:
  %i = phi i32 [ 0, %entry ], [ %i.next, %loop ]
  %j = phi i32 [ 0, %entry ], [ %j.next, %loop ]
  %cond = icmp slt i32 %i, 5
  %j.plus.step = add i32 %j, %step
  %j.next = select i1 %cond, i32 %j, i32 %j.plus.step
  %i.next = add nuw nsw i32 %i, 1
  %done = icmp eq i32 %i.next, %n
  br i1 %done, label %exit, label %loop

exit:
  ret void
}

; Step on LHS of the add: add %step, %j (vs add %j, %step).
define void @conditional_iv_step_lhs(i32 %n, i32 %step) {
; CHECK-LABEL: 'conditional_iv_step_lhs'
; CHECK-NEXT:  Classifying expressions for: @conditional_iv_step_lhs
; CHECK-NEXT:    %i = phi i32 [ 0, %entry ], [ %i.next, %loop ]
; CHECK-NEXT:    --> {0,+,1}<nuw><nsw><%loop> U: [0,-2147483648) S: [0,-2147483648) Exits: (-1 + %n) LoopDispositions: { %loop: Computable }
; CHECK-NEXT:    %j = phi i32 [ 0, %entry ], [ %j.next, %loop ]
; CHECK-NEXT:    --> {0,+[%cond],%step}<%loop> U: full-set S: full-set Exits: <<Unknown>> LoopDispositions: { %loop: Computable }
; CHECK-NEXT:    %j.plus.step = add i32 %step, %j
; CHECK-NEXT:    --> ({0,+[%cond],%step}<%loop> + %step) U: full-set S: full-set Exits: <<Unknown>> LoopDispositions: { %loop: Computable }
; CHECK-NEXT:    %j.next = select i1 %cond, i32 %j.plus.step, i32 %j
; CHECK-NEXT:    --> %j.next U: full-set S: full-set Exits: <<Unknown>> LoopDispositions: { %loop: Variant }
; CHECK-NEXT:    %i.next = add nuw nsw i32 %i, 1
; CHECK-NEXT:    --> {1,+,1}<nuw><nsw><%loop> U: [1,-2147483648) S: [1,-2147483648) Exits: %n LoopDispositions: { %loop: Computable }
; CHECK-NEXT:  Determining loop execution counts for: @conditional_iv_step_lhs
; CHECK-NEXT:  Loop %loop: backedge-taken count is (-1 + %n)
; CHECK-NEXT:  Loop %loop: constant max backedge-taken count is i32 -1
; CHECK-NEXT:  Loop %loop: symbolic max backedge-taken count is (-1 + %n)
; CHECK-NEXT:  Loop %loop: Trip multiple is 1
;
entry:
  br label %loop

loop:
  %i = phi i32 [ 0, %entry ], [ %i.next, %loop ]
  %j = phi i32 [ 0, %entry ], [ %j.next, %loop ]
  %cond = icmp sgt i32 %i, 10
  %j.plus.step = add i32 %step, %j
  %j.next = select i1 %cond, i32 %j.plus.step, i32 %j
  %i.next = add nuw nsw i32 %i, 1
  %done = icmp eq i32 %i.next, %n
  br i1 %done, label %exit, label %loop

exit:
  ret void
}

; Non-zero start value.
define void @conditional_iv_nonzero_start(i32 %n, i32 %start, i32 %step) {
; CHECK-LABEL: 'conditional_iv_nonzero_start'
; CHECK-NEXT:  Classifying expressions for: @conditional_iv_nonzero_start
; CHECK-NEXT:    %i = phi i32 [ 0, %entry ], [ %i.next, %loop ]
; CHECK-NEXT:    --> {0,+,1}<nuw><nsw><%loop> U: [0,-2147483648) S: [0,-2147483648) Exits: (-1 + %n) LoopDispositions: { %loop: Computable }
; CHECK-NEXT:    %j = phi i32 [ %start, %entry ], [ %j.next, %loop ]
; CHECK-NEXT:    --> {%start,+[%cond],%step}<%loop> U: full-set S: full-set Exits: <<Unknown>> LoopDispositions: { %loop: Computable }
; CHECK-NEXT:    %j.plus.step = add i32 %j, %step
; CHECK-NEXT:    --> ({%start,+[%cond],%step}<%loop> + %step) U: full-set S: full-set Exits: <<Unknown>> LoopDispositions: { %loop: Computable }
; CHECK-NEXT:    %j.next = select i1 %cond, i32 %j.plus.step, i32 %j
; CHECK-NEXT:    --> %j.next U: full-set S: full-set Exits: <<Unknown>> LoopDispositions: { %loop: Variant }
; CHECK-NEXT:    %i.next = add nuw nsw i32 %i, 1
; CHECK-NEXT:    --> {1,+,1}<nuw><nsw><%loop> U: [1,-2147483648) S: [1,-2147483648) Exits: %n LoopDispositions: { %loop: Computable }
; CHECK-NEXT:  Determining loop execution counts for: @conditional_iv_nonzero_start
; CHECK-NEXT:  Loop %loop: backedge-taken count is (-1 + %n)
; CHECK-NEXT:  Loop %loop: constant max backedge-taken count is i32 -1
; CHECK-NEXT:  Loop %loop: symbolic max backedge-taken count is (-1 + %n)
; CHECK-NEXT:  Loop %loop: Trip multiple is 1
;
entry:
  br label %loop

loop:
  %i = phi i32 [ 0, %entry ], [ %i.next, %loop ]
  %j = phi i32 [ %start, %entry ], [ %j.next, %loop ]
  %cond = icmp sgt i32 %i, 10
  %j.plus.step = add i32 %j, %step
  %j.next = select i1 %cond, i32 %j.plus.step, i32 %j
  %i.next = add nuw nsw i32 %i, 1
  %done = icmp eq i32 %i.next, %n
  br i1 %done, label %exit, label %loop

exit:
  ret void
}

; Constant-fold: Cond is always true -> degenerates to a plain AddRec {0,+,1}.
define void @conditional_iv_always_true(i32 %n) {
; CHECK-LABEL: 'conditional_iv_always_true'
; CHECK-NEXT:  Classifying expressions for: @conditional_iv_always_true
; CHECK-NEXT:    %i = phi i32 [ 0, %entry ], [ %i.next, %loop ]
; CHECK-NEXT:    --> {0,+,1}<nuw><nsw><%loop> U: [0,-2147483648) S: [0,-2147483648) Exits: (-1 + %n) LoopDispositions: { %loop: Computable }
; CHECK-NEXT:    %j = phi i32 [ 0, %entry ], [ %j.next, %loop ]
; CHECK-NEXT:    --> {0,+,1}<nuw><nsw><%loop> U: [0,-2147483648) S: [0,-2147483648) Exits: (-1 + %n) LoopDispositions: { %loop: Computable }
; CHECK-NEXT:    %j.plus1 = add i32 %j, 1
; CHECK-NEXT:    --> {1,+,1}<nuw><nsw><%loop> U: [1,-2147483648) S: [1,-2147483648) Exits: %n LoopDispositions: { %loop: Computable }
; CHECK-NEXT:    %j.next = select i1 true, i32 %j.plus1, i32 %j
; CHECK-NEXT:    --> {1,+,1}<nuw><nsw><%loop> U: [1,-2147483648) S: [1,-2147483648) Exits: %n LoopDispositions: { %loop: Computable }
; CHECK-NEXT:    %i.next = add nuw nsw i32 %i, 1
; CHECK-NEXT:    --> {1,+,1}<nuw><nsw><%loop> U: [1,-2147483648) S: [1,-2147483648) Exits: %n LoopDispositions: { %loop: Computable }
; CHECK-NEXT:  Determining loop execution counts for: @conditional_iv_always_true
; CHECK-NEXT:  Loop %loop: backedge-taken count is (-1 + %n)
; CHECK-NEXT:  Loop %loop: constant max backedge-taken count is i32 -1
; CHECK-NEXT:  Loop %loop: symbolic max backedge-taken count is (-1 + %n)
; CHECK-NEXT:  Loop %loop: Trip multiple is 1
;
entry:
  br label %loop

loop:
  %i = phi i32 [ 0, %entry ], [ %i.next, %loop ]
  %j = phi i32 [ 0, %entry ], [ %j.next, %loop ]
  %j.plus1 = add i32 %j, 1
  %j.next = select i1 true, i32 %j.plus1, i32 %j
  %i.next = add nuw nsw i32 %i, 1
  %done = icmp eq i32 %i.next, %n
  br i1 %done, label %exit, label %loop

exit:
  ret void
}

; Constant-fold: Cond is always false -> degenerates to Start.
define void @conditional_iv_always_false(i32 %n) {
; CHECK-LABEL: 'conditional_iv_always_false'
; CHECK-NEXT:  Classifying expressions for: @conditional_iv_always_false
; CHECK-NEXT:    %i = phi i32 [ 0, %entry ], [ %i.next, %loop ]
; CHECK-NEXT:    --> {0,+,1}<nuw><nsw><%loop> U: [0,-2147483648) S: [0,-2147483648) Exits: (-1 + %n) LoopDispositions: { %loop: Computable }
; CHECK-NEXT:    %j = phi i32 [ 7, %entry ], [ %j.next, %loop ]
; CHECK-NEXT:    --> 7 U: [7,8) S: [7,8) Exits: 7 LoopDispositions: { %loop: Invariant }
; CHECK-NEXT:    %j.plus1 = add i32 %j, 1
; CHECK-NEXT:    --> 8 U: [8,9) S: [8,9) Exits: 8 LoopDispositions: { %loop: Invariant }
; CHECK-NEXT:    %j.next = select i1 false, i32 %j.plus1, i32 %j
; CHECK-NEXT:    --> 7 U: [7,8) S: [7,8) Exits: 7 LoopDispositions: { %loop: Invariant }
; CHECK-NEXT:    %i.next = add nuw nsw i32 %i, 1
; CHECK-NEXT:    --> {1,+,1}<nuw><nsw><%loop> U: [1,-2147483648) S: [1,-2147483648) Exits: %n LoopDispositions: { %loop: Computable }
; CHECK-NEXT:  Determining loop execution counts for: @conditional_iv_always_false
; CHECK-NEXT:  Loop %loop: backedge-taken count is (-1 + %n)
; CHECK-NEXT:  Loop %loop: constant max backedge-taken count is i32 -1
; CHECK-NEXT:  Loop %loop: symbolic max backedge-taken count is (-1 + %n)
; CHECK-NEXT:  Loop %loop: Trip multiple is 1
;
entry:
  br label %loop

loop:
  %i = phi i32 [ 0, %entry ], [ %i.next, %loop ]
  %j = phi i32 [ 7, %entry ], [ %j.next, %loop ]
  %j.plus1 = add i32 %j, 1
  %j.next = select i1 false, i32 %j.plus1, i32 %j
  %i.next = add nuw nsw i32 %i, 1
  %done = icmp eq i32 %i.next, %n
  br i1 %done, label %exit, label %loop

exit:
  ret void
}

; Negative: non-invariant step (depends on the IV i) -> should NOT become a
; conditional AddRec. Expect SCEVUnknown for %j.
define void @neg_variant_step(i32 %n) {
; CHECK-LABEL: 'neg_variant_step'
; CHECK-NEXT:  Classifying expressions for: @neg_variant_step
; CHECK-NEXT:    %i = phi i32 [ 0, %entry ], [ %i.next, %loop ]
; CHECK-NEXT:    --> {0,+,1}<nuw><nsw><%loop> U: [0,-2147483648) S: [0,-2147483648) Exits: (-1 + %n) LoopDispositions: { %loop: Computable }
; CHECK-NEXT:    %j = phi i32 [ 0, %entry ], [ %j.next, %loop ]
; CHECK-NEXT:    --> %j U: full-set S: full-set Exits: <<Unknown>> LoopDispositions: { %loop: Variant }
; CHECK-NEXT:    %j.plus.i = add i32 %j, %i
; CHECK-NEXT:    --> ({0,+,1}<nuw><nsw><%loop> + %j) U: full-set S: full-set Exits: <<Unknown>> LoopDispositions: { %loop: Variant }
; CHECK-NEXT:    %j.next = select i1 %cond, i32 %j.plus.i, i32 %j
; CHECK-NEXT:    --> %j.next U: full-set S: full-set Exits: <<Unknown>> LoopDispositions: { %loop: Variant }
; CHECK-NEXT:    %i.next = add nuw nsw i32 %i, 1
; CHECK-NEXT:    --> {1,+,1}<nuw><nsw><%loop> U: [1,-2147483648) S: [1,-2147483648) Exits: %n LoopDispositions: { %loop: Computable }
; CHECK-NEXT:  Determining loop execution counts for: @neg_variant_step
; CHECK-NEXT:  Loop %loop: backedge-taken count is (-1 + %n)
; CHECK-NEXT:  Loop %loop: constant max backedge-taken count is i32 -1
; CHECK-NEXT:  Loop %loop: symbolic max backedge-taken count is (-1 + %n)
; CHECK-NEXT:  Loop %loop: Trip multiple is 1
;
entry:
  br label %loop

loop:
  %i = phi i32 [ 0, %entry ], [ %i.next, %loop ]
  %j = phi i32 [ 0, %entry ], [ %j.next, %loop ]
  %cond = icmp sgt i32 %i, 10
  %j.plus.i = add i32 %j, %i
  %j.next = select i1 %cond, i32 %j.plus.i, i32 %j
  %i.next = add nuw nsw i32 %i, 1
  %done = icmp eq i32 %i.next, %n
  br i1 %done, label %exit, label %loop

exit:
  ret void
}

; Negative: both select arms differ from the phi (neither is the unchanged
; case) -> not a conditional IV, should remain SCEVUnknown.
define void @neg_both_arms_advance(i32 %n, i32 %s1, i32 %s2) {
; CHECK-LABEL: 'neg_both_arms_advance'
; CHECK-NEXT:  Classifying expressions for: @neg_both_arms_advance
; CHECK-NEXT:    %i = phi i32 [ 0, %entry ], [ %i.next, %loop ]
; CHECK-NEXT:    --> {0,+,1}<nuw><nsw><%loop> U: [0,-2147483648) S: [0,-2147483648) Exits: (-1 + %n) LoopDispositions: { %loop: Computable }
; CHECK-NEXT:    %j = phi i32 [ 0, %entry ], [ %j.next, %loop ]
; CHECK-NEXT:    --> %j U: full-set S: full-set Exits: <<Unknown>> LoopDispositions: { %loop: Variant }
; CHECK-NEXT:    %j.plus.s1 = add i32 %j, %s1
; CHECK-NEXT:    --> (%s1 + %j) U: full-set S: full-set Exits: <<Unknown>> LoopDispositions: { %loop: Variant }
; CHECK-NEXT:    %j.plus.s2 = add i32 %j, %s2
; CHECK-NEXT:    --> (%s2 + %j) U: full-set S: full-set Exits: <<Unknown>> LoopDispositions: { %loop: Variant }
; CHECK-NEXT:    %j.next = select i1 %cond, i32 %j.plus.s1, i32 %j.plus.s2
; CHECK-NEXT:    --> %j.next U: full-set S: full-set Exits: <<Unknown>> LoopDispositions: { %loop: Variant }
; CHECK-NEXT:    %i.next = add nuw nsw i32 %i, 1
; CHECK-NEXT:    --> {1,+,1}<nuw><nsw><%loop> U: [1,-2147483648) S: [1,-2147483648) Exits: %n LoopDispositions: { %loop: Computable }
; CHECK-NEXT:  Determining loop execution counts for: @neg_both_arms_advance
; CHECK-NEXT:  Loop %loop: backedge-taken count is (-1 + %n)
; CHECK-NEXT:  Loop %loop: constant max backedge-taken count is i32 -1
; CHECK-NEXT:  Loop %loop: symbolic max backedge-taken count is (-1 + %n)
; CHECK-NEXT:  Loop %loop: Trip multiple is 1
;
entry:
  br label %loop

loop:
  %i = phi i32 [ 0, %entry ], [ %i.next, %loop ]
  %j = phi i32 [ 0, %entry ], [ %j.next, %loop ]
  %cond = icmp sgt i32 %i, 10
  %j.plus.s1 = add i32 %j, %s1
  %j.plus.s2 = add i32 %j, %s2
  %j.next = select i1 %cond, i32 %j.plus.s1, i32 %j.plus.s2
  %i.next = add nuw nsw i32 %i, 1
  %done = icmp eq i32 %i.next, %n
  br i1 %done, label %exit, label %loop

exit:
  ret void
}

; Motivating compressed-store shape: j indexes the output array and only
; advances when cond is true. We check that SCEV classifies both the IV j
; and the resulting address %c.gep in terms of the conditional AddRec.
define void @compressed_store(ptr %a, ptr %b, ptr %c, i32 %n) {
; CHECK-LABEL: 'compressed_store'
; CHECK-NEXT:  Classifying expressions for: @compressed_store
; CHECK-NEXT:    %i = phi i32 [ 0, %entry ], [ %i.next, %loop ]
; CHECK-NEXT:    --> {0,+,1}<nuw><nsw><%loop> U: [0,-2147483648) S: [0,-2147483648) Exits: (-1 + %n) LoopDispositions: { %loop: Computable }
; CHECK-NEXT:    %j = phi i32 [ 0, %entry ], [ %j.next, %loop ]
; CHECK-NEXT:    --> {0,+[%cond],1}<%loop> U: full-set S: full-set Exits: <<Unknown>> LoopDispositions: { %loop: Computable }
; CHECK-NEXT:    %i.ext = zext i32 %i to i64
; CHECK-NEXT:    --> {0,+,1}<nuw><nsw><%loop> U: [0,4294967296) S: [0,4294967296) Exits: (zext i32 (-1 + %n) to i64) LoopDispositions: { %loop: Computable }
; CHECK-NEXT:    %a.gep = getelementptr inbounds i32, ptr %a, i64 %i.ext
; CHECK-NEXT:    --> {%a,+,4}<nuw><%loop> U: full-set S: full-set Exits: ((4 * (zext i32 (-1 + %n) to i64))<nuw><nsw> + %a) LoopDispositions: { %loop: Computable }
; CHECK-NEXT:    %b.gep = getelementptr inbounds i32, ptr %b, i64 %i.ext
; CHECK-NEXT:    --> {%b,+,4}<nuw><%loop> U: full-set S: full-set Exits: ((4 * (zext i32 (-1 + %n) to i64))<nuw><nsw> + %b) LoopDispositions: { %loop: Computable }
; CHECK-NEXT:    %va = load i32, ptr %a.gep, align 4
; CHECK-NEXT:    --> %va U: full-set S: full-set Exits: <<Unknown>> LoopDispositions: { %loop: Variant }
; CHECK-NEXT:    %vb = load i32, ptr %b.gep, align 4
; CHECK-NEXT:    --> %vb U: full-set S: full-set Exits: <<Unknown>> LoopDispositions: { %loop: Variant }
; CHECK-NEXT:    %sum = add i32 %va, %vb
; CHECK-NEXT:    --> (%vb + %va) U: full-set S: full-set Exits: <<Unknown>> LoopDispositions: { %loop: Variant }
; CHECK-NEXT:    %j.ext = zext i32 %j to i64
; CHECK-NEXT:    --> (zext i32 {0,+[%cond],1}<%loop> to i64) U: [0,4294967296) S: [0,4294967296) Exits: <<Unknown>> LoopDispositions: { %loop: Computable }
; CHECK-NEXT:    %c.gep = getelementptr inbounds i32, ptr %c, i64 %j.ext
; CHECK-NEXT:    --> ((4 * (zext i32 {0,+[%cond],1}<%loop> to i64))<nuw><nsw> + %c)<nuw> U: full-set S: full-set Exits: <<Unknown>> LoopDispositions: { %loop: Computable }
; CHECK-NEXT:    %j.plus1 = add i32 %j, 1
; CHECK-NEXT:    --> (1 + {0,+[%cond],1}<%loop>) U: full-set S: full-set Exits: <<Unknown>> LoopDispositions: { %loop: Computable }
; CHECK-NEXT:    %j.next = select i1 %cond, i32 %j.plus1, i32 %j
; CHECK-NEXT:    --> %j.next U: full-set S: full-set Exits: <<Unknown>> LoopDispositions: { %loop: Variant }
; CHECK-NEXT:    %i.next = add nuw nsw i32 %i, 1
; CHECK-NEXT:    --> {1,+,1}<nuw><nsw><%loop> U: [1,-2147483648) S: [1,-2147483648) Exits: %n LoopDispositions: { %loop: Computable }
; CHECK-NEXT:  Determining loop execution counts for: @compressed_store
; CHECK-NEXT:  Loop %loop: backedge-taken count is (-1 + %n)
; CHECK-NEXT:  Loop %loop: constant max backedge-taken count is i32 -1
; CHECK-NEXT:  Loop %loop: symbolic max backedge-taken count is (-1 + %n)
; CHECK-NEXT:  Loop %loop: Trip multiple is 1
;
entry:
  br label %loop

loop:
  %i = phi i32 [ 0, %entry ], [ %i.next, %loop ]
  %j = phi i32 [ 0, %entry ], [ %j.next, %loop ]
  %i.ext = zext i32 %i to i64
  %a.gep = getelementptr inbounds i32, ptr %a, i64 %i.ext
  %b.gep = getelementptr inbounds i32, ptr %b, i64 %i.ext
  %va = load i32, ptr %a.gep
  %vb = load i32, ptr %b.gep
  %sum = add i32 %va, %vb
  %cond = icmp ne i32 %va, 0
  %j.ext = zext i32 %j to i64
  %c.gep = getelementptr inbounds i32, ptr %c, i64 %j.ext
  store i32 %sum, ptr %c.gep
  %j.plus1 = add i32 %j, 1
  %j.next = select i1 %cond, i32 %j.plus1, i32 %j
  %i.next = add nuw nsw i32 %i, 1
  %done = icmp eq i32 %i.next, %n
  br i1 %done, label %exit, label %loop

exit:
  ret void
}
