; NOTE: Assertions have been autogenerated by utils/update_analyze_test_checks.py UTC_ARGS: --version 2
; RUN: opt -disable-output "-passes=print<scalar-evolution>" < %s 2>&1 | FileCheck %s

; Tests for recognition of SCEVConditionalAddRecExpr from the "split-CFG /
; phi-merge form". Companion to conditional-addrec-select.ll.
;
; Shape: the backedge value of the loop-header phi is itself a merge PHI
; whose two incoming values come from opposite sides of a conditional
; branch. This is what clang emits before simplifycfg/instcombine fold the
; conditional update into a select.
;
;   header:
;     j = phi(Start, j.next)   ; backedge value is a merge PHI
;     br i1 %Cond, %take, %merge
;   take:
;     %inc = add j, Step
;     br label %merge
;   merge:
;     %j.next = phi i32 [ %inc, %take ], [ %j, %header ]
;     br label %latch
;     ...

; Canonical triangle: take-block branches to merge, skip-edge is direct
; from the gate (the header itself here) to merge.
define void @split_cfg_canonical(i32 %n) {
; CHECK-LABEL: 'split_cfg_canonical'
; CHECK-NEXT:  Classifying expressions for: @split_cfg_canonical
; CHECK-NEXT:    %i = phi i32 [ 0, %entry ], [ %i.next, %latch ]
; CHECK-NEXT:    --> {0,+,1}<nuw><nsw><%header> U: [0,-2147483648) S: [0,-2147483648) Exits: (-1 + %n) LoopDispositions: { %header: Computable }
; CHECK-NEXT:    %j = phi i32 [ 0, %entry ], [ %j.next, %latch ]
; CHECK-NEXT:    --> {0,+[%cond],1}<%header> U: full-set S: full-set Exits: <<Unknown>> LoopDispositions: { %header: Computable }
; CHECK-NEXT:    %j.plus1 = add i32 %j, 1
; CHECK-NEXT:    --> (1 + {0,+[%cond],1}<%header>) U: full-set S: full-set Exits: <<Unknown>> LoopDispositions: { %header: Computable }
; CHECK-NEXT:    %j.next = phi i32 [ %j.plus1, %take ], [ %j, %header ]
; CHECK-NEXT:    --> %j.next U: full-set S: full-set Exits: <<Unknown>> LoopDispositions: { %header: Variant }
; CHECK-NEXT:    %i.next = add nuw nsw i32 %i, 1
; CHECK-NEXT:    --> {1,+,1}<nuw><nsw><%header> U: [1,-2147483648) S: [1,-2147483648) Exits: %n LoopDispositions: { %header: Computable }
; CHECK-NEXT:  Determining loop execution counts for: @split_cfg_canonical
; CHECK-NEXT:  Loop %header: backedge-taken count is (-1 + %n)
; CHECK-NEXT:  Loop %header: constant max backedge-taken count is i32 -1
; CHECK-NEXT:  Loop %header: symbolic max backedge-taken count is (-1 + %n)
; CHECK-NEXT:  Loop %header: Trip multiple is 1
;
entry:
  br label %header

header:
  %i = phi i32 [ 0, %entry ], [ %i.next, %latch ]
  %j = phi i32 [ 0, %entry ], [ %j.next, %latch ]
  %cond = icmp sgt i32 %i, 10
  br i1 %cond, label %take, label %merge

take:
  %j.plus1 = add i32 %j, 1
  br label %merge

merge:
  %j.next = phi i32 [ %j.plus1, %take ], [ %j, %header ]
  br label %latch

latch:
  %i.next = add nuw nsw i32 %i, 1
  %done = icmp eq i32 %i.next, %n
  br i1 %done, label %exit, label %header

exit:
  ret void
}

; Swapped edges: `br i1 %cond, label %skip, label %take`. The condition's
; TRUE edge is the skip side, so the cond should be auto-negated.
define void @split_cfg_swapped_edges(i32 %n, i32 %step) {
; CHECK-LABEL: 'split_cfg_swapped_edges'
; CHECK-NEXT:  Classifying expressions for: @split_cfg_swapped_edges
; CHECK-NEXT:    %i = phi i32 [ 0, %entry ], [ %i.next, %latch ]
; CHECK-NEXT:    --> {0,+,1}<nuw><nsw><%header> U: [0,-2147483648) S: [0,-2147483648) Exits: (-1 + %n) LoopDispositions: { %header: Computable }
; CHECK-NEXT:    %j = phi i32 [ 0, %entry ], [ %j.next, %latch ]
; CHECK-NEXT:    --> {0,+[(true + %cond)],%step}<%header> U: full-set S: full-set Exits: <<Unknown>> LoopDispositions: { %header: Computable }
; CHECK-NEXT:    %j.plus.step = add i32 %j, %step
; CHECK-NEXT:    --> ({0,+[(true + %cond)],%step}<%header> + %step) U: full-set S: full-set Exits: <<Unknown>> LoopDispositions: { %header: Computable }
; CHECK-NEXT:    %j.next = phi i32 [ %j, %header ], [ %j.plus.step, %take ]
; CHECK-NEXT:    --> %j.next U: full-set S: full-set Exits: <<Unknown>> LoopDispositions: { %header: Variant }
; CHECK-NEXT:    %i.next = add nuw nsw i32 %i, 1
; CHECK-NEXT:    --> {1,+,1}<nuw><nsw><%header> U: [1,-2147483648) S: [1,-2147483648) Exits: %n LoopDispositions: { %header: Computable }
; CHECK-NEXT:  Determining loop execution counts for: @split_cfg_swapped_edges
; CHECK-NEXT:  Loop %header: backedge-taken count is (-1 + %n)
; CHECK-NEXT:  Loop %header: constant max backedge-taken count is i32 -1
; CHECK-NEXT:  Loop %header: symbolic max backedge-taken count is (-1 + %n)
; CHECK-NEXT:  Loop %header: Trip multiple is 1
;
entry:
  br label %header

header:
  %i = phi i32 [ 0, %entry ], [ %i.next, %latch ]
  %j = phi i32 [ 0, %entry ], [ %j.next, %latch ]
  %cond = icmp slt i32 %i, 5
  br i1 %cond, label %merge, label %take

take:
  %j.plus.step = add i32 %j, %step
  br label %merge

merge:
  %j.next = phi i32 [ %j, %header ], [ %j.plus.step, %take ]
  br label %latch

latch:
  %i.next = add nuw nsw i32 %i, 1
  %done = icmp eq i32 %i.next, %n
  br i1 %done, label %exit, label %header

exit:
  ret void
}

; Step on LHS of add: add %step, %j (vs add %j, %step).
define void @split_cfg_step_lhs(i32 %n, i32 %step) {
; CHECK-LABEL: 'split_cfg_step_lhs'
; CHECK-NEXT:  Classifying expressions for: @split_cfg_step_lhs
; CHECK-NEXT:    %i = phi i32 [ 0, %entry ], [ %i.next, %latch ]
; CHECK-NEXT:    --> {0,+,1}<nuw><nsw><%header> U: [0,-2147483648) S: [0,-2147483648) Exits: (-1 + %n) LoopDispositions: { %header: Computable }
; CHECK-NEXT:    %j = phi i32 [ 0, %entry ], [ %j.next, %latch ]
; CHECK-NEXT:    --> {0,+[%cond],%step}<%header> U: full-set S: full-set Exits: <<Unknown>> LoopDispositions: { %header: Computable }
; CHECK-NEXT:    %j.plus.step = add i32 %step, %j
; CHECK-NEXT:    --> ({0,+[%cond],%step}<%header> + %step) U: full-set S: full-set Exits: <<Unknown>> LoopDispositions: { %header: Computable }
; CHECK-NEXT:    %j.next = phi i32 [ %j.plus.step, %take ], [ %j, %header ]
; CHECK-NEXT:    --> %j.next U: full-set S: full-set Exits: <<Unknown>> LoopDispositions: { %header: Variant }
; CHECK-NEXT:    %i.next = add nuw nsw i32 %i, 1
; CHECK-NEXT:    --> {1,+,1}<nuw><nsw><%header> U: [1,-2147483648) S: [1,-2147483648) Exits: %n LoopDispositions: { %header: Computable }
; CHECK-NEXT:  Determining loop execution counts for: @split_cfg_step_lhs
; CHECK-NEXT:  Loop %header: backedge-taken count is (-1 + %n)
; CHECK-NEXT:  Loop %header: constant max backedge-taken count is i32 -1
; CHECK-NEXT:  Loop %header: symbolic max backedge-taken count is (-1 + %n)
; CHECK-NEXT:  Loop %header: Trip multiple is 1
;
entry:
  br label %header

header:
  %i = phi i32 [ 0, %entry ], [ %i.next, %latch ]
  %j = phi i32 [ 0, %entry ], [ %j.next, %latch ]
  %cond = icmp sgt i32 %i, 10
  br i1 %cond, label %take, label %merge

take:
  %j.plus.step = add i32 %step, %j
  br label %merge

merge:
  %j.next = phi i32 [ %j.plus.step, %take ], [ %j, %header ]
  br label %latch

latch:
  %i.next = add nuw nsw i32 %i, 1
  %done = icmp eq i32 %i.next, %n
  br i1 %done, label %exit, label %header

exit:
  ret void
}

; Non-zero start value.
define void @split_cfg_nonzero_start(i32 %n, i32 %start, i32 %step) {
; CHECK-LABEL: 'split_cfg_nonzero_start'
; CHECK-NEXT:  Classifying expressions for: @split_cfg_nonzero_start
; CHECK-NEXT:    %i = phi i32 [ 0, %entry ], [ %i.next, %latch ]
; CHECK-NEXT:    --> {0,+,1}<nuw><nsw><%header> U: [0,-2147483648) S: [0,-2147483648) Exits: (-1 + %n) LoopDispositions: { %header: Computable }
; CHECK-NEXT:    %j = phi i32 [ %start, %entry ], [ %j.next, %latch ]
; CHECK-NEXT:    --> {%start,+[%cond],%step}<%header> U: full-set S: full-set Exits: <<Unknown>> LoopDispositions: { %header: Computable }
; CHECK-NEXT:    %j.plus.step = add i32 %j, %step
; CHECK-NEXT:    --> ({%start,+[%cond],%step}<%header> + %step) U: full-set S: full-set Exits: <<Unknown>> LoopDispositions: { %header: Computable }
; CHECK-NEXT:    %j.next = phi i32 [ %j.plus.step, %take ], [ %j, %header ]
; CHECK-NEXT:    --> %j.next U: full-set S: full-set Exits: <<Unknown>> LoopDispositions: { %header: Variant }
; CHECK-NEXT:    %i.next = add nuw nsw i32 %i, 1
; CHECK-NEXT:    --> {1,+,1}<nuw><nsw><%header> U: [1,-2147483648) S: [1,-2147483648) Exits: %n LoopDispositions: { %header: Computable }
; CHECK-NEXT:  Determining loop execution counts for: @split_cfg_nonzero_start
; CHECK-NEXT:  Loop %header: backedge-taken count is (-1 + %n)
; CHECK-NEXT:  Loop %header: constant max backedge-taken count is i32 -1
; CHECK-NEXT:  Loop %header: symbolic max backedge-taken count is (-1 + %n)
; CHECK-NEXT:  Loop %header: Trip multiple is 1
;
entry:
  br label %header

header:
  %i = phi i32 [ 0, %entry ], [ %i.next, %latch ]
  %j = phi i32 [ %start, %entry ], [ %j.next, %latch ]
  %cond = icmp sgt i32 %i, 10
  br i1 %cond, label %take, label %merge

take:
  %j.plus.step = add i32 %j, %step
  br label %merge

merge:
  %j.next = phi i32 [ %j.plus.step, %take ], [ %j, %header ]
  br label %latch

latch:
  %i.next = add nuw nsw i32 %i, 1
  %done = icmp eq i32 %i.next, %n
  br i1 %done, label %exit, label %header

exit:
  ret void
}

; Always-true gate: `br i1 true, ...`. Constant-folds to a plain AddRec.
define void @split_cfg_always_true_gate(i32 %n) {
; CHECK-LABEL: 'split_cfg_always_true_gate'
; CHECK-NEXT:  Classifying expressions for: @split_cfg_always_true_gate
; CHECK-NEXT:    %i = phi i32 [ 0, %entry ], [ %i.next, %latch ]
; CHECK-NEXT:    --> {0,+,1}<nuw><nsw><%header> U: [0,-2147483648) S: [0,-2147483648) Exits: (-1 + %n) LoopDispositions: { %header: Computable }
; CHECK-NEXT:    %j = phi i32 [ 0, %entry ], [ %j.next, %latch ]
; CHECK-NEXT:    --> {0,+,1}<nuw><nsw><%header> U: [0,-2147483648) S: [0,-2147483648) Exits: (-1 + %n) LoopDispositions: { %header: Computable }
; CHECK-NEXT:    %j.plus1 = add i32 %j, 1
; CHECK-NEXT:    --> {1,+,1}<nuw><nsw><%header> U: [1,-2147483648) S: [1,-2147483648) Exits: %n LoopDispositions: { %header: Computable }
; CHECK-NEXT:    %j.next = phi i32 [ %j.plus1, %take ], [ %j, %header ]
; CHECK-NEXT:    --> {1,+,1}<nuw><nsw><%header> U: [1,-2147483648) S: [1,-2147483648) Exits: %n LoopDispositions: { %header: Computable }
; CHECK-NEXT:    %i.next = add nuw nsw i32 %i, 1
; CHECK-NEXT:    --> {1,+,1}<nuw><nsw><%header> U: [1,-2147483648) S: [1,-2147483648) Exits: %n LoopDispositions: { %header: Computable }
; CHECK-NEXT:  Determining loop execution counts for: @split_cfg_always_true_gate
; CHECK-NEXT:  Loop %header: backedge-taken count is (-1 + %n)
; CHECK-NEXT:  Loop %header: constant max backedge-taken count is i32 -1
; CHECK-NEXT:  Loop %header: symbolic max backedge-taken count is (-1 + %n)
; CHECK-NEXT:  Loop %header: Trip multiple is 1
;
entry:
  br label %header

header:
  %i = phi i32 [ 0, %entry ], [ %i.next, %latch ]
  %j = phi i32 [ 0, %entry ], [ %j.next, %latch ]
  br i1 true, label %take, label %merge

take:
  %j.plus1 = add i32 %j, 1
  br label %merge

merge:
  %j.next = phi i32 [ %j.plus1, %take ], [ %j, %header ]
  br label %latch

latch:
  %i.next = add nuw nsw i32 %i, 1
  %done = icmp eq i32 %i.next, %n
  br i1 %done, label %exit, label %header

exit:
  ret void
}

; Always-false gate: `br i1 false, ...`. Constant-folds to Start.
define void @split_cfg_always_false_gate(i32 %n) {
; CHECK-LABEL: 'split_cfg_always_false_gate'
; CHECK-NEXT:  Classifying expressions for: @split_cfg_always_false_gate
; CHECK-NEXT:    %i = phi i32 [ 0, %entry ], [ %i.next, %latch ]
; CHECK-NEXT:    --> {0,+,1}<nuw><nsw><%header> U: [0,-2147483648) S: [0,-2147483648) Exits: (-1 + %n) LoopDispositions: { %header: Computable }
; CHECK-NEXT:    %j = phi i32 [ 7, %entry ], [ %j.next, %latch ]
; CHECK-NEXT:    --> 7 U: [7,8) S: [7,8) Exits: 7 LoopDispositions: { %header: Invariant }
; CHECK-NEXT:    %j.plus1 = add i32 %j, 1
; CHECK-NEXT:    --> 8 U: [8,9) S: [8,9) Exits: 8 LoopDispositions: { %header: Invariant }
; CHECK-NEXT:    %j.next = phi i32 [ %j.plus1, %take ], [ %j, %header ]
; CHECK-NEXT:    --> 7 U: [7,8) S: [7,8) Exits: 7 LoopDispositions: { %header: Invariant }
; CHECK-NEXT:    %i.next = add nuw nsw i32 %i, 1
; CHECK-NEXT:    --> {1,+,1}<nuw><nsw><%header> U: [1,-2147483648) S: [1,-2147483648) Exits: %n LoopDispositions: { %header: Computable }
; CHECK-NEXT:  Determining loop execution counts for: @split_cfg_always_false_gate
; CHECK-NEXT:  Loop %header: backedge-taken count is (-1 + %n)
; CHECK-NEXT:  Loop %header: constant max backedge-taken count is i32 -1
; CHECK-NEXT:  Loop %header: symbolic max backedge-taken count is (-1 + %n)
; CHECK-NEXT:  Loop %header: Trip multiple is 1
;
entry:
  br label %header

header:
  %i = phi i32 [ 0, %entry ], [ %i.next, %latch ]
  %j = phi i32 [ 7, %entry ], [ %j.next, %latch ]
  br i1 false, label %take, label %merge

take:
  %j.plus1 = add i32 %j, 1
  br label %merge

merge:
  %j.next = phi i32 [ %j.plus1, %take ], [ %j, %header ]
  br label %latch

latch:
  %i.next = add nuw nsw i32 %i, 1
  %done = icmp eq i32 %i.next, %n
  br i1 %done, label %exit, label %header

exit:
  ret void
}

; Diamond: both arms of the branch are non-trivial blocks that branch to
; merge. Proves recognition does not depend on one edge being direct.
define void @split_cfg_diamond(ptr %sink, i32 %n) {
; CHECK-LABEL: 'split_cfg_diamond'
; CHECK-NEXT:  Classifying expressions for: @split_cfg_diamond
; CHECK-NEXT:    %i = phi i32 [ 0, %entry ], [ %i.next, %latch ]
; CHECK-NEXT:    --> {0,+,1}<nuw><nsw><%header> U: [0,-2147483648) S: [0,-2147483648) Exits: (-1 + %n) LoopDispositions: { %header: Computable }
; CHECK-NEXT:    %j = phi i32 [ 0, %entry ], [ %j.next, %latch ]
; CHECK-NEXT:    --> {0,+[%cond],1}<%header> U: full-set S: full-set Exits: <<Unknown>> LoopDispositions: { %header: Computable }
; CHECK-NEXT:    %j.plus1 = add i32 %j, 1
; CHECK-NEXT:    --> (1 + {0,+[%cond],1}<%header>) U: full-set S: full-set Exits: <<Unknown>> LoopDispositions: { %header: Computable }
; CHECK-NEXT:    %j.next = phi i32 [ %j.plus1, %take ], [ %j, %skip ]
; CHECK-NEXT:    --> %j.next U: full-set S: full-set Exits: <<Unknown>> LoopDispositions: { %header: Variant }
; CHECK-NEXT:    %i.next = add nuw nsw i32 %i, 1
; CHECK-NEXT:    --> {1,+,1}<nuw><%header> U: [1,0) S: [1,0) Exits: %n LoopDispositions: { %header: Computable }
; CHECK-NEXT:  Determining loop execution counts for: @split_cfg_diamond
; CHECK-NEXT:  Loop %header: backedge-taken count is (-1 + %n)
; CHECK-NEXT:  Loop %header: constant max backedge-taken count is i32 -1
; CHECK-NEXT:  Loop %header: symbolic max backedge-taken count is (-1 + %n)
; CHECK-NEXT:  Loop %header: Trip multiple is 1
;
entry:
  br label %header

header:
  %i = phi i32 [ 0, %entry ], [ %i.next, %latch ]
  %j = phi i32 [ 0, %entry ], [ %j.next, %latch ]
  %cond = icmp sgt i32 %i, 10
  br i1 %cond, label %take, label %skip

take:
  %j.plus1 = add i32 %j, 1
  store volatile i32 42, ptr %sink
  br label %merge

skip:
  store volatile i32 99, ptr %sink
  br label %merge

merge:
  %j.next = phi i32 [ %j.plus1, %take ], [ %j, %skip ]
  br label %latch

latch:
  %i.next = add nuw nsw i32 %i, 1
  %done = icmp eq i32 %i.next, %n
  br i1 %done, label %exit, label %header

exit:
  ret void
}

; Motivating compressed-store shape from benchmarks/compress_store/filter_pack.c:
;   for (int i = 0; i < n; ++i) if (cond[i]) dst[j++] = src[i];
; Gate is a separate block from the header (for.body in the original). The
; take-arm stores and increments; the skip-edge goes direct from gate to
; merge.
define void @split_cfg_filter_pack(ptr %src, ptr %cond, ptr %dst, i32 %n) {
; CHECK-LABEL: 'split_cfg_filter_pack'
; CHECK-NEXT:  Classifying expressions for: @split_cfg_filter_pack
; CHECK-NEXT:    %i.0 = phi i32 [ 0, %entry ], [ %inc5, %for.inc ]
; CHECK-NEXT:    --> {0,+,1}<nuw><nsw><%for.cond> U: [0,-2147483648) S: [0,-2147483648) Exits: (0 smax %n) LoopDispositions: { %for.cond: Computable }
; CHECK-NEXT:    %j.0 = phi i32 [ 0, %entry ], [ %j.1, %for.inc ]
; CHECK-NEXT:    --> {0,+[%tobool],1}<%for.cond> U: full-set S: full-set Exits: <<Unknown>> LoopDispositions: { %for.cond: Computable }
; CHECK-NEXT:    %i.ext = sext i32 %i.0 to i64
; CHECK-NEXT:    --> {0,+,1}<nuw><nsw><%for.cond> U: [0,2147483648) S: [0,2147483648) Exits: (zext i32 (0 smax %n) to i64) LoopDispositions: { %for.cond: Computable }
; CHECK-NEXT:    %c.gep = getelementptr inbounds i8, ptr %cond, i64 %i.ext
; CHECK-NEXT:    --> {%cond,+,1}<nw><%for.cond> U: full-set S: full-set Exits: ((zext i32 (0 smax %n) to i64) + %cond) LoopDispositions: { %for.cond: Computable }
; CHECK-NEXT:    %c.load = load i8, ptr %c.gep, align 1
; CHECK-NEXT:    --> %c.load U: full-set S: full-set Exits: <<Unknown>> LoopDispositions: { %for.cond: Variant }
; CHECK-NEXT:    %s.gep = getelementptr inbounds i32, ptr %src, i64 %i.ext
; CHECK-NEXT:    --> {%src,+,4}<nw><%for.cond> U: full-set S: full-set Exits: ((4 * (zext i32 (0 smax %n) to i64))<nuw><nsw> + %src) LoopDispositions: { %for.cond: Computable }
; CHECK-NEXT:    %s.load = load i32, ptr %s.gep, align 4
; CHECK-NEXT:    --> %s.load U: full-set S: full-set Exits: <<Unknown>> LoopDispositions: { %for.cond: Variant }
; CHECK-NEXT:    %inc = add nsw i32 %j.0, 1
; CHECK-NEXT:    --> (1 + {0,+[%tobool],1}<%for.cond>) U: full-set S: full-set Exits: <<Unknown>> LoopDispositions: { %for.cond: Computable }
; CHECK-NEXT:    %j.ext = sext i32 %j.0 to i64
; CHECK-NEXT:    --> (sext i32 {0,+[%tobool],1}<%for.cond> to i64) U: [-2147483648,2147483648) S: [-2147483648,2147483648) Exits: <<Unknown>> LoopDispositions: { %for.cond: Computable }
; CHECK-NEXT:    %d.gep = getelementptr inbounds i32, ptr %dst, i64 %j.ext
; CHECK-NEXT:    --> ((4 * (sext i32 {0,+[%tobool],1}<%for.cond> to i64))<nsw> + %dst) U: full-set S: full-set Exits: <<Unknown>> LoopDispositions: { %for.cond: Computable }
; CHECK-NEXT:    %j.1 = phi i32 [ %inc, %if.then ], [ %j.0, %for.body ]
; CHECK-NEXT:    --> %j.1 U: full-set S: full-set Exits: <<Unknown>> LoopDispositions: { %for.cond: Variant }
; CHECK-NEXT:    %inc5 = add nsw i32 %i.0, 1
; CHECK-NEXT:    --> {1,+,1}<nuw><%for.cond> U: [1,-2147483647) S: [1,-2147483647) Exits: (1 + (0 smax %n))<nuw> LoopDispositions: { %for.cond: Computable }
; CHECK-NEXT:  Determining loop execution counts for: @split_cfg_filter_pack
; CHECK-NEXT:  Loop %for.cond: backedge-taken count is (0 smax %n)
; CHECK-NEXT:  Loop %for.cond: constant max backedge-taken count is i32 2147483647
; CHECK-NEXT:  Loop %for.cond: symbolic max backedge-taken count is (0 smax %n)
; CHECK-NEXT:  Loop %for.cond: Trip multiple is 1
;
entry:
  br label %for.cond

for.cond:
  %i.0 = phi i32 [ 0, %entry ], [ %inc5, %for.inc ]
  %j.0 = phi i32 [ 0, %entry ], [ %j.1, %for.inc ]
  %cmp = icmp slt i32 %i.0, %n
  br i1 %cmp, label %for.body, label %for.end

for.body:
  %i.ext = sext i32 %i.0 to i64
  %c.gep = getelementptr inbounds i8, ptr %cond, i64 %i.ext
  %c.load = load i8, ptr %c.gep
  %tobool = icmp ne i8 %c.load, 0
  br i1 %tobool, label %if.then, label %if.end

if.then:
  %s.gep = getelementptr inbounds i32, ptr %src, i64 %i.ext
  %s.load = load i32, ptr %s.gep
  %inc = add nsw i32 %j.0, 1
  %j.ext = sext i32 %j.0 to i64
  %d.gep = getelementptr inbounds i32, ptr %dst, i64 %j.ext
  store i32 %s.load, ptr %d.gep
  br label %if.end

if.end:
  %j.1 = phi i32 [ %inc, %if.then ], [ %j.0, %for.body ]
  br label %for.inc

for.inc:
  %inc5 = add nsw i32 %i.0, 1
  br label %for.cond

for.end:
  ret void
}

; Negative: non-invariant step (depends on the IV i) -> not recognized.
define void @neg_split_cfg_variant_step(i32 %n) {
; CHECK-LABEL: 'neg_split_cfg_variant_step'
; CHECK-NEXT:  Classifying expressions for: @neg_split_cfg_variant_step
; CHECK-NEXT:    %i = phi i32 [ 0, %entry ], [ %i.next, %latch ]
; CHECK-NEXT:    --> {0,+,1}<nuw><nsw><%header> U: [0,-2147483648) S: [0,-2147483648) Exits: (-1 + %n) LoopDispositions: { %header: Computable }
; CHECK-NEXT:    %j = phi i32 [ 0, %entry ], [ %j.next, %latch ]
; CHECK-NEXT:    --> %j U: full-set S: full-set Exits: <<Unknown>> LoopDispositions: { %header: Variant }
; CHECK-NEXT:    %j.plus.i = add i32 %j, %i
; CHECK-NEXT:    --> ({0,+,1}<nuw><nsw><%header> + %j) U: full-set S: full-set Exits: <<Unknown>> LoopDispositions: { %header: Variant }
; CHECK-NEXT:    %j.next = phi i32 [ %j.plus.i, %take ], [ %j, %header ]
; CHECK-NEXT:    --> %j.next U: full-set S: full-set Exits: <<Unknown>> LoopDispositions: { %header: Variant }
; CHECK-NEXT:    %i.next = add nuw nsw i32 %i, 1
; CHECK-NEXT:    --> {1,+,1}<nuw><nsw><%header> U: [1,-2147483648) S: [1,-2147483648) Exits: %n LoopDispositions: { %header: Computable }
; CHECK-NEXT:  Determining loop execution counts for: @neg_split_cfg_variant_step
; CHECK-NEXT:  Loop %header: backedge-taken count is (-1 + %n)
; CHECK-NEXT:  Loop %header: constant max backedge-taken count is i32 -1
; CHECK-NEXT:  Loop %header: symbolic max backedge-taken count is (-1 + %n)
; CHECK-NEXT:  Loop %header: Trip multiple is 1
;
entry:
  br label %header

header:
  %i = phi i32 [ 0, %entry ], [ %i.next, %latch ]
  %j = phi i32 [ 0, %entry ], [ %j.next, %latch ]
  %cond = icmp sgt i32 %i, 10
  br i1 %cond, label %take, label %merge

take:
  %j.plus.i = add i32 %j, %i
  br label %merge

merge:
  %j.next = phi i32 [ %j.plus.i, %take ], [ %j, %header ]
  br label %latch

latch:
  %i.next = add nuw nsw i32 %i, 1
  %done = icmp eq i32 %i.next, %n
  br i1 %done, label %exit, label %header

exit:
  ret void
}

; Negative: both arms advance (neither arm equals the phi unchanged).
define void @neg_split_cfg_both_advance(i32 %n, i32 %s1, i32 %s2) {
; CHECK-LABEL: 'neg_split_cfg_both_advance'
; CHECK-NEXT:  Classifying expressions for: @neg_split_cfg_both_advance
; CHECK-NEXT:    %i = phi i32 [ 0, %entry ], [ %i.next, %latch ]
; CHECK-NEXT:    --> {0,+,1}<nuw><nsw><%header> U: [0,-2147483648) S: [0,-2147483648) Exits: (-1 + %n) LoopDispositions: { %header: Computable }
; CHECK-NEXT:    %j = phi i32 [ 0, %entry ], [ %j.next, %latch ]
; CHECK-NEXT:    --> %j U: full-set S: full-set Exits: <<Unknown>> LoopDispositions: { %header: Variant }
; CHECK-NEXT:    %j.plus.s1 = add i32 %j, %s1
; CHECK-NEXT:    --> (%s1 + %j) U: full-set S: full-set Exits: <<Unknown>> LoopDispositions: { %header: Variant }
; CHECK-NEXT:    %j.plus.s2 = add i32 %j, %s2
; CHECK-NEXT:    --> (%s2 + %j) U: full-set S: full-set Exits: <<Unknown>> LoopDispositions: { %header: Variant }
; CHECK-NEXT:    %j.next = phi i32 [ %j.plus.s1, %take ], [ %j.plus.s2, %skip ]
; CHECK-NEXT:    --> %j.next U: full-set S: full-set Exits: <<Unknown>> LoopDispositions: { %header: Variant }
; CHECK-NEXT:    %i.next = add nuw nsw i32 %i, 1
; CHECK-NEXT:    --> {1,+,1}<nuw><nsw><%header> U: [1,-2147483648) S: [1,-2147483648) Exits: %n LoopDispositions: { %header: Computable }
; CHECK-NEXT:  Determining loop execution counts for: @neg_split_cfg_both_advance
; CHECK-NEXT:  Loop %header: backedge-taken count is (-1 + %n)
; CHECK-NEXT:  Loop %header: constant max backedge-taken count is i32 -1
; CHECK-NEXT:  Loop %header: symbolic max backedge-taken count is (-1 + %n)
; CHECK-NEXT:  Loop %header: Trip multiple is 1
;
entry:
  br label %header

header:
  %i = phi i32 [ 0, %entry ], [ %i.next, %latch ]
  %j = phi i32 [ 0, %entry ], [ %j.next, %latch ]
  %cond = icmp sgt i32 %i, 10
  br i1 %cond, label %take, label %skip

take:
  %j.plus.s1 = add i32 %j, %s1
  br label %merge

skip:
  %j.plus.s2 = add i32 %j, %s2
  br label %merge

merge:
  %j.next = phi i32 [ %j.plus.s1, %take ], [ %j.plus.s2, %skip ]
  br label %latch

latch:
  %i.next = add nuw nsw i32 %i, 1
  %done = icmp eq i32 %i.next, %n
  br i1 %done, label %exit, label %header

exit:
  ret void
}

; Negative: merge PHI has three incoming values -> getOperandsForSelectLikePHI
; rejects it (require getNumIncomingValues() == 2).
define void @neg_split_cfg_three_preds(i32 %n) {
; CHECK-LABEL: 'neg_split_cfg_three_preds'
; CHECK-NEXT:  Classifying expressions for: @neg_split_cfg_three_preds
; CHECK-NEXT:    %i = phi i32 [ 0, %entry ], [ %i.next, %latch ]
; CHECK-NEXT:    --> {0,+,1}<nuw><nsw><%header> U: [0,-2147483648) S: [0,-2147483648) Exits: (-1 + %n) LoopDispositions: { %header: Computable }
; CHECK-NEXT:    %j = phi i32 [ 0, %entry ], [ %j.next, %latch ]
; CHECK-NEXT:    --> %j U: full-set S: full-set Exits: <<Unknown>> LoopDispositions: { %header: Variant }
; CHECK-NEXT:    %j.plus1 = add i32 %j, 1
; CHECK-NEXT:    --> (1 + %j) U: full-set S: full-set Exits: <<Unknown>> LoopDispositions: { %header: Variant }
; CHECK-NEXT:    %j.plus2 = add i32 %j, 2
; CHECK-NEXT:    --> (2 + %j) U: full-set S: full-set Exits: <<Unknown>> LoopDispositions: { %header: Variant }
; CHECK-NEXT:    %j.next = phi i32 [ %j.plus1, %take1 ], [ %j.plus2, %take2 ], [ %j, %skip ]
; CHECK-NEXT:    --> %j.next U: full-set S: full-set Exits: <<Unknown>> LoopDispositions: { %header: Variant }
; CHECK-NEXT:    %i.next = add nuw nsw i32 %i, 1
; CHECK-NEXT:    --> {1,+,1}<nuw><nsw><%header> U: [1,-2147483648) S: [1,-2147483648) Exits: %n LoopDispositions: { %header: Computable }
; CHECK-NEXT:  Determining loop execution counts for: @neg_split_cfg_three_preds
; CHECK-NEXT:  Loop %header: backedge-taken count is (-1 + %n)
; CHECK-NEXT:  Loop %header: constant max backedge-taken count is i32 -1
; CHECK-NEXT:  Loop %header: symbolic max backedge-taken count is (-1 + %n)
; CHECK-NEXT:  Loop %header: Trip multiple is 1
;
entry:
  br label %header

header:
  %i = phi i32 [ 0, %entry ], [ %i.next, %latch ]
  %j = phi i32 [ 0, %entry ], [ %j.next, %latch ]
  switch i32 %i, label %skip [
    i32 0, label %take1
    i32 1, label %take2
  ]

take1:
  %j.plus1 = add i32 %j, 1
  br label %merge

take2:
  %j.plus2 = add i32 %j, 2
  br label %merge

skip:
  br label %merge

merge:
  %j.next = phi i32 [ %j.plus1, %take1 ], [ %j.plus2, %take2 ], [ %j, %skip ]
  br label %latch

latch:
  %i.next = add nuw nsw i32 %i, 1
  %done = icmp eq i32 %i.next, %n
  br i1 %done, label %exit, label %header

exit:
  ret void
}
